services:
    weblablv.amazon_ses_client.ses_client_email_sender:
        class: WebLabLv\Bundle\AmazonSdkSesWrapperBundle\Service\SesClientSenderService
        calls:
            - [ setProfile,         ['%weblablv.amazon_ses_client.profile%'                 ]]
            - [ setRegion,          ['%weblablv.amazon_ses_client.region%'                  ]]
            - [ setCredentialsPath, ['%weblablv.amazon_ses_client.path_to_credentials_file%']]
            - [ setVersion,         ['%weblablv.amazon_ses_client.version%'                 ]]
