services:
    weblablv.amazon_sdk_ses_wrapper.ses_client_email_sender:
        class: WebLabLv\AmazonSdkSesWrapper\Service\SesClientEmailSender
        arguments:
            - '%weblablv_amazon_sdk_ses_wrapper.profile%'
            - '%weblablv_amazon_sdk_ses_wrapper.credentials.access_key_id%'
            - '%weblablv_amazon_sdk_ses_wrapper.credentials.access_secret_key%'
            - '%weblablv_amazon_sdk_ses_wrapper.region%'
